(* ::Package:: *)

(* ::Input:: *)
(*(* Minimized function *)*)
(*R1[x_]:=Cos[x^5-x+3+2^(1/3)];*)
(*R2[x_]:=ArcTan[x^3-5Sqrt[2]x-4]/(Sqrt[6]x+Sqrt[3]);*)
(*f[x_]:=R1@x+R2@x+18/10;*)
(*(* Interval *)*)
(*{A, B}={0, 1};*)
(*l1=B-A;*)
(**)
(*Plot[f@t,{t,0,1},*)
(*PlotRange->All,PlotStyle->Red,PlotLegends->{"f(t)"},AxesLabel->{"t","f(t)"},ImageSize->Medium,AxesStyle->Black*)
(*]*)
(**)
(*(* ###################### *)*)
(*(* ### DICHOTOMY METHOD ### *)*)
(*(* ###################### *)*)
(*(* Consts *)*)
(*\[CurlyEpsilon]=10^-6;*)
(*\[Delta]=\[CurlyEpsilon]/10;*)
(*(* Computation proceeds until length of 'l' becomes smaller that '\[CurlyEpsilon]' *)*)
(*{a,b}={A,B};*)
(*l=l1;*)
(*k=1;*)
(*L = {l};*)
(*While[l>\[CurlyEpsilon],*)
(*x1=(a+b)/2-\[Delta];*)
(*x2=(a+b)/2+\[Delta];*)
(*(* Depending on f@x1 and f@x2 reduce the interval from the left or right *)*)
(*If[f@x1>=f@x2,a=x1,b=x2];*)
(*l=b-a;*)
(*k++;*)
(*(* Save values of 'l' for later visualization *)*)
(*AppendTo[L,l];*)
(*];*)
(*(* As an approx minumim we take the midpoint of the resulting interval *)*)
(*x=(a+b)/2;*)
(*K=k-1;*)
(*Framed@Framed@"Dichotomy method"*)
(*Row[{"\[CurlyEpsilon] = ", \[CurlyEpsilon]//N}]*)
(*Row[{"Argmin: x = ", x//N}]*)
(*Row[{"Iterations: K = ", K}]*)
(*Row[{"Computations of f[x]: 2K = ", 2K}]*)
(*(* Using number of iterations 'K' and list of interval lenghts 'L' plot how interval of indeterminacy changes throughout iterations *)*)
(*(* Plot 2 versions of progression: analythical and numeric *)*)
(*anPlot=Plot[(l1-2\[Delta])/2^(i-1)+2\[Delta],{i,1,K},*)
(*PlotRange->All,PlotStyle->Blue,PlotLegends->{"Analythical plot"},AxesLabel->{"Iterations","Interval of indeterminacy"},ImageSize->Medium*)
(*];*)
(*numPlot=ListLinePlot[Table[{i,L[[i]]},{i,1,K}],*)
(*PlotRange->All,PlotStyle->{Red,Dashed,Thick},PlotLegends->{"Numeric plot"}*)
(*];*)
(*Show[anPlot,numPlot,AxesStyle->Black]*)
(**)
(*(* ########################### *)*)
(*(* ### GOLDEN-SECTION SEARCH ### *)*)
(*(* ########################### *)*)
(*(* Consts *)*)
(*\[Lambda]=(Sqrt[5]-2)/2//N;*)
(*\[CurlyEpsilon]=10^-6;*)
(*(* The main difference compared to dichotomy method method is a lesser number of function computations (~2 times less), that, however, comes with a significanly reduced convergence speed *)*)
(*{a,b}={A,B};*)
(*l=l1;*)
(*k=1;*)
(*L={l};*)
(*(* The method itself *)*)
(*\[Delta]=\[Lambda] l;*)
(*{x1,x2}={(a+b)/2-\[Delta],(a+b)/2+\[Delta]};*)
(*{f1,f2}={N@f@x1,N@f@x2};*)
(*While[l>\[CurlyEpsilon],*)
(*If[f1>=f2,*)
(*a=x1;l=b-a;\[Delta]=\[Lambda] l;x1=x2;x2=(a+b)/2+\[Delta];f1=f2;f2=f@x2,*)
(*b=x2;l=b-a;\[Delta]=\[Lambda] l;x2=x1;x1=(a+b)/2-\[Delta];f2=f1;f1=f@x1;*)
(*];*)
(*k++;*)
(*(* Save values of 'l' for later visualization *)*)
(*AppendTo[L,l];*)
(*];*)
(*(* As an approx minumim we take the midpoint of the resulting interval *)*)
(*x=(a+b)/2;*)
(*K=k-1;*)
(*Framed@Framed@"Golden-section search"*)
(*Row[{"\[CurlyEpsilon] = ", \[CurlyEpsilon]//N}]*)
(*Row[{"Argmin: x = ", x//N}]*)
(*Row[{"Iterations: K = ", K}]*)
(*Row[{"Computations of f[x]: K+1 = ", K+1}]*)
(*(* Using number of iterations 'K' and list of interval lenghts 'L' plot how interval of indeterminacy changes throughout iterations *)*)
(*(* Plot 2 versions of progression: analythical and numeric *)*)
(*anPlot=Plot[l1 ((Sqrt[5]-1)/2)^(i-1),{i,1,K},*)
(*PlotRange->All,PlotStyle->Blue,PlotLegends->{"Analythical plot"},AxesLabel->{"Iterations","Interval of indeterminacy"},ImageSize->Medium*)
(*];*)
(*numPlot=ListLinePlot[Table[{i,L[[i]]},{i,1,K}],*)
(*PlotRange->All,PlotStyle->{Red,Dashed,Thick},PlotLegends->{"Numeric plot"}*)
(*];*)
(*Show[anPlot,numPlot,AxesStyle->Black]*)
